### ISSUE TITLE
ZHFST files website not valid

### ISSUE THREAD

**Issue by hnliu-git** [divvun/ck-ospell#10]
Hi, I would like to download the ZHFST files for Northern Sami but unfortunately, the website below is no longer valid. Could you tell me how to download them?

- http://divvun.no/static_files/zhfsts/se.zhfst

**Comment by snomos** [comment]
Files are not stored at that URL anymore. Speller packages can be installed using Divvun Manager, downloadable from https://divvun.no.

Presently there is no support for downloading ZHFST files directly, but if you can extract from a macOS `.pkg` file or run a windows `.exe` installer, you should find the ZHFST file inside. Links to the latest build are:

- macOS: https://pahkat.uit.no/main/download/speller-sme?platform=macos&channel=nightly
- Windows: https://pahkat.uit.no/main/download/speller-sme?platform=windows&channel=nightly
